name: go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: skiplistmap

    - uses: actions/checkout@v2
      with:
        repository: kazu/elist_head
        ref: 2c24bde5ba616f2bf716d8fe007c9da91a57a831
        path: elist_head

    - uses: actions/checkout@v2
      with:
        repository: kazu/loncha
        ref: 1a71ffebf3c97146f935f257d249261470a54b46
        path: loncha

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.27.1

    - name: Build
      working-directory: skiplistmap
      run: |
        ulimit -v 4194304
        go build -v ./...

    - name: Test
      working-directory: skiplistmap
      run: make ci
